[project]
name = "odoo-addons-oca-manufacture-reporting"
version = "19.0.20260903.1"
dependencies = [
    "odoo-addon-mrp_bom_current_stock==19.0.*",
    "odoo-addon-mrp_flattened_bom_xlsx==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
